# Generated by Django 4.2.18 on 2026-06-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0031_companylink_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('emoji', models.CharField(blank=True, default='📁', max_length=16)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('legacy_peopleforce_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to='employees.employee')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
