# Generated by Codex on 2026-06-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0029_set_work_table_sync_targets'),
        ('announcements', '0002_announcementreaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='kind',
            field=models.CharField(
                choices=[('announcement', 'Оголошення'), ('poll', 'Опитування')],
                db_index=True,
                default='announcement',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='announcement',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='poll_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AnnouncementPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_index', models.PositiveSmallIntegerField()),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='announcements.announcement')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_poll_votes', to='employees.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='announcementpollvote',
            index=models.Index(fields=['announcement', 'option_index'], name='ann_poll_option_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementpollvote',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='uniq_ann_poll_user'),
        ),
    ]
