# Generated by Django 5.2.11 on 2026-06-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleForceImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('dry_run', 'Dry run')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='pf_import_run_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeopleForceImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=20)),
                ('entity_type', models.CharField(max_length=80)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('message', models.CharField(max_length=500)),
                ('raw_fragment', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='integrations.peopleforceimportrun')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['run', 'severity'], name='pf_import_issue_run_idx'), models.Index(fields=['entity_type', 'external_id'], name='pf_import_issue_entity_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeopleForceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=80)),
                ('external_id', models.CharField(max_length=160)),
                ('endpoint', models.CharField(blank=True, max_length=240)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(blank=True, max_length=128)),
                ('fetched_at', models.DateTimeField()),
                ('mapping_status', models.CharField(choices=[('raw_only', 'Raw only'), ('mapped', 'Mapped'), ('skipped', 'Skipped'), ('error', 'Error')], default='raw_only', max_length=20)),
                ('hr_model', models.CharField(blank=True, max_length=120)),
                ('hr_object_id', models.CharField(blank=True, max_length=120)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='integrations.peopleforceimportrun')),
            ],
            options={
                'ordering': ['entity_type', 'external_id'],
                'indexes': [models.Index(fields=['entity_type', 'mapping_status'], name='pf_entity_type_status_idx'), models.Index(fields=['hr_model', 'hr_object_id'], name='pf_entity_hr_object_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'external_id'), name='uniq_pf_entity_type_external')],
            },
        ),
    ]
