# Generated by Django 5.2.11 on 2026-06-24 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_division_employmenttype_joblevel_team_teammembership_and_more'),
        ('integrations', '0001_initial'),
        ('skud', '0002_timecorrectionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleForceCompatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=12)),
                ('path', models.CharField(max_length=260)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('processed_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('partial', 'Partial'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('payload_hash', models.CharField(blank=True, max_length=128)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['method', 'path', '-created_at'], name='pfcompat_req_lookup_idx'), models.Index(fields=['processed_status', '-created_at'], name='pfcompat_req_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeopleForceCompatTimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_peopleforce_entry_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('legacy_peopleforce_employee_id', models.CharField(db_index=True, max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('date', models.DateField()),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unsubmitted', max_length=20)),
                ('entry_type', models.CharField(default='working', max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peopleforce_compat_entry', to='skud.attendanceperiod')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peopleforce_compat_timesheet_entries', to='employees.employee')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_entries', to='integrations.peopleforcecompatrequest')),
            ],
            options={
                'ordering': ['-starts_at', 'legacy_peopleforce_employee_id'],
                'indexes': [models.Index(fields=['legacy_peopleforce_employee_id', 'date'], name='pfcompat_ts_emp_date_idx'), models.Index(fields=['employee', 'date'], name='pfcompat_ts_hr_emp_date_idx'), models.Index(fields=['status', 'date'], name='pfcompat_ts_status_date_idx'), models.Index(fields=['deleted_at'], name='pfcompat_ts_deleted_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('legacy_peopleforce_employee_id', 'starts_at', 'ends_at'), name='uniq_pfcompat_active_ts_entry'), models.UniqueConstraint(condition=models.Q(('legacy_peopleforce_entry_id', ''), _negated=True), fields=('legacy_peopleforce_entry_id',), name='uniq_pfcompat_pf_entry_id')],
            },
        ),
    ]
