# Generated by Django 4.2.18 on 2026-06-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_peopleforcecompatrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleForceWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=120)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('remote_addr', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic', '-created_at'], name='pfwebhook_topic_time_idx'), models.Index(fields=['status', '-created_at'], name='pfwebhook_status_time_idx')],
            },
        ),
    ]
