# Generated by Django 5.2.11 on 2026-06-24 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeattachment',
            name='legacy_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgeattachment',
            name='legacy_peopleforce_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='knowledgeattachment',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgecategory',
            name='legacy_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgecategory',
            name='legacy_peopleforce_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='knowledgecategory',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='body_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='legacy_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='legacy_peopleforce_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['legacy_peopleforce_id'], name='knowledge_doc_pf_idx'),
        ),
    ]
