# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_knowledgeattachment_legacy_payload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="cover_url",
            field=models.URLField(blank=True),
        ),
    ]
