# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_knowledgedocument_cover_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgecategory",
            name="audience_employee_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="knowledgecategory",
            name="audience_filters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="knowledgecategory",
            name="icon_emoji",
            field=models.CharField(blank=True, default="📄", max_length=16),
        ),
        migrations.AddField(
            model_name="knowledgecategory",
            name="visibility_mode",
            field=models.CharField(choices=[("all", "All"), ("specific", "Specific people")], default="all", max_length=20),
        ),
    ]
