# Generated by Codex on 2026-06-24

from django.db import migrations


def restore_peopleforce_category_tree(apps, schema_editor):
    KnowledgeCategory = apps.get_model("knowledge", "KnowledgeCategory")
    categories = list(KnowledgeCategory.objects.all())
    by_legacy_id = {str(category.legacy_peopleforce_id): category for category in categories if category.legacy_peopleforce_id}

    for category in categories:
        payload = category.legacy_payload or {}
        parent_legacy_id = payload.get("parent_id")
        parent = by_legacy_id.get(str(parent_legacy_id)) if parent_legacy_id else None
        icon = (payload.get("emoji") or category.icon_emoji or "📄")[:16]

        update_fields = []
        if category.parent_id != (parent.pk if parent else None):
            category.parent = parent
            update_fields.append("parent")
        if category.icon_emoji != icon:
            category.icon_emoji = icon
            update_fields.append("icon_emoji")
        if update_fields:
            category.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0004_knowledgecategory_audience_icon"),
    ]

    operations = [
        migrations.RunPython(restore_peopleforce_category_tree, noop_reverse),
    ]
