# Generated by Django 5.2.11 on 2026-06-24 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_division_employmenttype_joblevel_team_teammembership_and_more'),
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_peopleforce_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('effective_on', models.DateField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('policy_name', models.CharField(blank=True, max_length=180)),
                ('policy_activity_type', models.CharField(blank=True, max_length=80)),
                ('policy_counted_as', models.CharField(blank=True, max_length=80)),
                ('legacy_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['employee', 'leave_type', '-effective_on'],
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='legacy_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='legacy_peopleforce_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='tracking_time_in',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='legacy_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='legacy_peopleforce_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='unit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['legacy_peopleforce_id'], name='leave_request_pf_idx'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='leave.leavetype'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_peopleforce_id', ''), _negated=True), fields=('employee', 'leave_type', 'legacy_peopleforce_id'), name='uniq_leave_balance_pf'),
        ),
    ]
