# Generated by Django 4.2.18 on 2026-06-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leavetype_icon_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='unit',
            field=models.CharField(blank=True, choices=[('days', 'У днях'), ('hours', 'У годинах')], default='days', help_text='Одиниця відстеження відсутності (days|hours)', max_length=40),
        ),
    ]
