# Generated by Django 5.2.11 on 2026-06-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_employeecertificate_attachment_name_and_more'),
        ('leave', '0005_normalize_leavetype_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeavePolicyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('legacy_peopleforce_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policy_assignments', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_assignments', to='leave.leavetype')),
            ],
            options={
                'ordering': ['employee', 'leave_type', '-effective_on'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('legacy_peopleforce_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('policy_type', models.CharField(choices=[('accrual', 'З нарахуванням'), ('manual', 'Без нарахування'), ('external', 'Зовнішній баланс')], default='manual', max_length=24)),
                ('activity_type', models.CharField(choices=[('not_working_paid', 'Неробочі, оплачувані'), ('not_working_unpaid', 'Неробочі, неоплачувані'), ('working_paid', 'Робочі, оплачувані')], default='not_working_paid', max_length=32)),
                ('counted_as', models.CharField(choices=[('working_days', 'Робочі дні'), ('calendar_days', 'Календарні дні')], default='working_days', max_length=24)),
                ('visibility', models.CharField(choices=[('everyone', 'Для всіх'), ('self_only', 'Для себе')], default='everyone', max_length=24)),
                ('instructions_html', models.TextField(blank=True)),
                ('prevent_overlapping_requests', models.BooleanField(default=True)),
                ('forbid_probation_requests', models.BooleanField(default=False)),
                ('forbid_breakdown_edit', models.BooleanField(default=False)),
                ('restrict_adjustments_for_employees', models.BooleanField(default=False)),
                ('direct_reports_only', models.BooleanField(default=False)),
                ('min_daily_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('min_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('min_notice_days', models.PositiveIntegerField(blank=True, null=True)),
                ('max_notice_days', models.PositiveIntegerField(blank=True, null=True)),
                ('approval_enabled', models.BooleanField(default=True)),
                ('skip_unassigned_approvers', models.BooleanField(default=False)),
                ('allow_substitute_approvers', models.BooleanField(default=False)),
                ('approver_steps', models.JSONField(blank=True, default=list)),
                ('rounding_method', models.CharField(choices=[('nearest', 'До найближчого'), ('down', 'Вниз'), ('up', 'Вгору')], default='nearest', max_length=24)),
                ('rounding_precision', models.CharField(choices=[('two_decimals', 'Два знаки після коми'), ('one_decimal', 'Один знак після коми'), ('integer', 'Ціле число')], default='two_decimals', max_length=24)),
                ('allow_withdraw', models.BooleanField(default=True)),
                ('mandatory_comment', models.BooleanField(default=False)),
                ('allow_attachments', models.BooleanField(default=False)),
                ('notify_approver', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_payload', models.JSONField(blank=True, default=dict)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leave.leavetype')),
            ],
            options={
                'ordering': ['leave_type__order', 'leave_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('opening_balance', 'Початковий баланс'), ('accrual', 'Нарахування'), ('request', 'Запит'), ('adjustment', 'Коригування'), ('carryover', 'Перенесення'), ('expiration', 'Списання'), ('import', 'Імпорт')], max_length=32)),
                ('occurred_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=260)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=180)),
                ('legacy_peopleforce_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='leave.employeeleavepolicyassignment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_ledger_entries', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='leave.leavetype')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='leave.leavepolicy')),
            ],
            options={
                'ordering': ['employee', 'leave_type', 'occurred_on', 'id'],
            },
        ),
        migrations.AddField(
            model_name='employeeleavepolicyassignment',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='leave.leavepolicy'),
        ),
        migrations.CreateModel(
            name='LeavePolicyAccrualRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('start_delay_amount', models.PositiveIntegerField(default=0)),
                ('start_delay_unit', models.CharField(choices=[('days', 'Дні'), ('months', 'Місяці'), ('years', 'Роки')], default='months', max_length=12)),
                ('start_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frequency', models.CharField(choices=[('none', 'Немає'), ('monthly', 'Щомісяця'), ('yearly', 'Щороку'), ('weekly', 'Щотижня')], default='monthly', max_length=16)),
                ('accrual_timing', models.CharField(choices=[('period_start', 'Початок періоду'), ('period_end', 'Кінець періоду')], default='period_start', max_length=16)),
                ('first_accrual', models.CharField(choices=[('proportional', 'Пропорційна'), ('full', 'Повна'), ('none', 'Не нараховувати')], default='proportional', max_length=16)),
                ('max_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carryover_mode', models.CharField(choices=[('none', 'Немає'), ('all', 'Усе'), ('limited', 'Обмежено')], default='none', max_length=12)),
                ('carryover_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carryover_expire_months', models.PositiveIntegerField(default=0)),
                ('carryover_day', models.PositiveSmallIntegerField(default=1)),
                ('carryover_month', models.PositiveSmallIntegerField(default=1)),
                ('seniority_bonus_enabled', models.BooleanField(default=False)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_rule', to='leave.leavepolicy')),
            ],
            options={
                'ordering': ['policy__leave_type__order', 'policy__name'],
            },
        ),
        migrations.AddIndex(
            model_name='leavepolicy',
            index=models.Index(fields=['leave_type', 'is_active'], name='leave_policy_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='leavepolicy',
            index=models.Index(fields=['policy_type', 'is_active'], name='leave_policy_kind_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_peopleforce_id', ''), _negated=True), fields=('legacy_peopleforce_id',), name='uniq_leave_policy_pf'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('leave_type', 'name'), name='uniq_active_leave_policy_name'),
        ),
        migrations.AddIndex(
            model_name='leaveledgerentry',
            index=models.Index(fields=['employee', 'leave_type', 'occurred_on'], name='leave_ledger_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveledgerentry',
            index=models.Index(fields=['assignment', 'kind'], name='leave_ledger_assign_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaveledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_leave_ledger_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='leaveledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_peopleforce_id', ''), _negated=True), fields=('legacy_peopleforce_id',), name='uniq_leave_ledger_pf'),
        ),
        migrations.AddIndex(
            model_name='employeeleavepolicyassignment',
            index=models.Index(fields=['employee', 'leave_type', 'is_active'], name='leave_assign_employee_type_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeleavepolicyassignment',
            index=models.Index(fields=['policy', 'is_active'], name='leave_assign_policy_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeleavepolicyassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_peopleforce_id', ''), _negated=True), fields=('legacy_peopleforce_id',), name='uniq_leave_assignment_pf'),
        ),
    ]
