# Generated by Django 4.2.18 on 2026-07-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetResponsibilityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('scope_type', models.CharField(choices=[('location', 'Локація'), ('department', 'Департамент')], max_length=20)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, max_length=200)),
                ('engineer_user_id', models.IntegerField(blank=True, null=True)),
                ('engineer_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('last_applied_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_responsibility_zones',
                'ordering': ['-created_at'],
            },
        ),
    ]
