# Generated by Django 4.2.18 on 2026-07-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_employeecertificate_attachment_name_and_more'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('city', 'Місто'), ('clinic', 'Клініка'), ('floor', 'Поверх'), ('cabinet', 'Кабінет')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('cmms_location_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('engineer_user_id', models.IntegerField(blank=True, null=True)),
                ('engineer_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='physical_locations', to='employees.department')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.physicallocation')),
            ],
            options={
                'db_table': 'asset_physical_locations',
                'ordering': ['order', 'name'],
            },
        ),
    ]
