# Generated by Django 4.2.18 on 2026-07-01 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_employeecertificate_attachment_name_and_more'),
        ('assets', '0003_asset_assettype_assetphoto_assetcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicallocation',
            name='engineer_name',
        ),
        migrations.RemoveField(
            model_name='physicallocation',
            name='engineer_user_id',
        ),
        migrations.AddField(
            model_name='physicallocation',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_locations', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='AssetOwnershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_creation', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_events', to='assets.asset')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.physicallocation')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
            ],
            options={
                'db_table': 'asset_ownership_events',
                'ordering': ['changed_at', 'id'],
            },
        ),
    ]
