# Generated by Django 4.2.18 on 2026-07-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_physicallocation_engineer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetphoto',
            name='content_type',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
