# Generated by Django 5.2.11 on 2026-06-26 08:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0017_holidaypolicy_clinic_holiday_policy_ref_holiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=160)),
                ('phone_normalized', models.CharField(db_index=True, max_length=32)),
                ('source', models.CharField(choices=[('shared_bot', 'Shared Telegram bot')], default='shared_bot', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to='employees.employee')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AuthAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('telegram_link_requested', 'Telegram link requested'), ('telegram_linked', 'Telegram linked'), ('login_code_requested', 'Login code requested'), ('login_code_sent', 'Login code sent'), ('login_succeeded', 'Login succeeded'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('access_denied', 'Access denied')], db_index=True, max_length=60)),
                ('result', models.CharField(choices=[('ok', 'OK'), ('denied', 'Denied'), ('failed', 'Failed'), ('conflict', 'Conflict'), ('not_found', 'Not found'), ('locked', 'Locked')], db_index=True, max_length=30)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=32)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_audit_events', to='employees.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_auth_audit_events', to=settings.AUTH_USER_MODEL)),
                ('telegram_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='access.employeetelegramlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramLoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=160)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_login_codes', to='employees.employee')),
                ('telegram_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_codes', to='access.employeetelegramlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employeetelegramlink',
            index=models.Index(fields=['is_active', 'phone_normalized'], name='tg_link_active_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetelegramlink',
            index=models.Index(fields=['is_active', 'telegram_chat_id'], name='tg_link_active_chat_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeetelegramlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('telegram_chat_id',), name='uniq_active_telegram_chat_id'),
        ),
        migrations.AddIndex(
            model_name='authauditevent',
            index=models.Index(fields=['event', 'result', '-created_at'], name='auth_audit_event_result_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditevent',
            index=models.Index(fields=['employee', '-created_at'], name='auth_audit_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditevent',
            index=models.Index(fields=['user', '-created_at'], name='auth_audit_user_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramlogincode',
            index=models.Index(fields=['employee', '-created_at'], name='tg_code_employee_created_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramlogincode',
            index=models.Index(fields=['employee', 'consumed_at'], name='tg_code_employee_used_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramlogincode',
            index=models.Index(fields=['expires_at', 'consumed_at'], name='tg_code_expiry_used_idx'),
        ),
    ]
