# Generated by Django 4.2.18 on 2026-06-30 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_employeecertificate_attachment_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('system', 'Системна'), ('custom', 'Кастомна')], default='custom', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_membership_computed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_code', models.CharField(max_length=120)),
                ('level', models.CharField(blank=True, max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='access.accessrole')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRoleAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('role_created', 'Роль створено'), ('role_updated', 'Роль оновлено'), ('role_deleted', 'Роль видалено'), ('permission_granted', 'Право видано'), ('permission_revoked', 'Право відкликано'), ('assignment_created', 'Призначення створено'), ('assignment_updated', 'Призначення оновлено'), ('assignment_removed', 'Призначення знято')], db_index=True, max_length=40)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audit_events', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='access.accessrole')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccessRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_system_computed', models.BooleanField(default=False)),
                ('scope_type', models.CharField(choices=[('self', 'Себе'), ('all_company', 'Вся компанія'), ('direct_reports', 'Прямі підлеглі'), ('direct_and_indirect_reports', 'Прямі та непрямі підлеглі'), ('team_members', 'Члени команди'), ('clinic', 'Клініка'), ('department', 'Відділ'), ('division', 'Підрозділ'), ('explicit_employees', 'Явний список'), ('custom_conditions', 'Кастомні умови')], default='self', max_length=40)),
                ('scope_payload', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_role_assignments', to='employees.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='access.accessrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='accessrolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission_code'), name='access_role_permission_unique'),
        ),
        migrations.AddIndex(
            model_name='accessroleauditevent',
            index=models.Index(fields=['action', '-created_at'], name='access_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='accessroleauditevent',
            index=models.Index(fields=['role', '-created_at'], name='access_audit_role_idx'),
        ),
        migrations.AddIndex(
            model_name='accessroleassignment',
            index=models.Index(fields=['role', 'is_active'], name='access_assignment_role_idx'),
        ),
        migrations.AddIndex(
            model_name='accessroleassignment',
            index=models.Index(fields=['user', 'is_active'], name='access_assignment_user_idx'),
        ),
        migrations.AddIndex(
            model_name='accessroleassignment',
            index=models.Index(fields=['employee', 'is_active'], name='access_assignment_emp_idx'),
        ),
    ]
