# Generated by Django 4.2.18 on 2026-07-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_accessrole_accessrolepermission_accessroleauditevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authauditevent',
            name='event',
            field=models.CharField(choices=[('telegram_link_requested', 'Telegram link requested'), ('telegram_linked', 'Telegram linked'), ('login_code_requested', 'Login code requested'), ('login_code_sent', 'Login code sent'), ('login_succeeded', 'Login succeeded'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('session_expired', 'Session expired'), ('access_denied', 'Access denied')], db_index=True, max_length=60),
        ),
    ]
