# Generated by Django 5.2.11 on 2026-06-24 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='employees.clinic')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='employees.department')),
            ],
            options={
                'ordering': ['clinic__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_baf_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('external_fotopacients_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('legacy_peopleforce_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('phone2', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('dismissed', 'Dismissed'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('hired_on', models.DateField(blank=True, null=True)),
                ('dismissed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.clinic')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEmployeeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('baf', 'BAF'), ('fotopacients', 'FotoPacients'), ('peopleforce_legacy', 'PeopleForce legacy')], max_length=40)),
                ('external_id', models.CharField(max_length=160)),
                ('raw_hash', models.CharField(blank=True, max_length=128)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='employees.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subordinate_assignments', to='employees.employee')),
            ],
            options={
                'ordering': ['employee__last_name', '-valid_from'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['clinic', 'is_active'], name='department_clinic_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('clinic', 'name'), name='uniq_department_clinic_name'),
        ),
        migrations.AddIndex(
            model_name='externalemployeelink',
            index=models.Index(fields=['employee', 'source'], name='external_employee_link_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalemployeelink',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_external_employee_source_id'),
        ),
        migrations.AddIndex(
            model_name='managerassignment',
            index=models.Index(fields=['employee', 'valid_from', 'valid_to'], name='mgr_employee_period_idx'),
        ),
        migrations.AddIndex(
            model_name='managerassignment',
            index=models.Index(fields=['manager', 'valid_from', 'valid_to'], name='mgr_manager_period_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'clinic', 'department'], name='employee_scope_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employee_name_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone'], name='employee_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employee_email_idx'),
        ),
    ]
