# Generated by Django 5.2.11 on 2026-06-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('baf', 'BAF'), ('fotopacients', 'FotoPacients'), ('peopleforce_legacy', 'PeopleForce legacy')], max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('dry_run', 'Dry run')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', 'status', '-started_at'], name='employee_import_run_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('external_fotopacients_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'medical specialties',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['external_fotopacients_id'], name='medical_specialty_ext_idx')],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_specialties',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employees.medicalspecialty'),
        ),
        migrations.CreateModel(
            name='EmployeeImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('message', models.CharField(max_length=500)),
                ('raw_fragment', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='employees.employeeimportrun')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['run', 'severity'], name='employee_import_issue_idx')],
            },
        ),
    ]
