# Generated by Django 5.2.11 on 2026-06-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_division_employmenttype_joblevel_team_teammembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_peopleforce_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('legacy_payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('legacy_peopleforce_id', ''), _negated=True), fields=('legacy_peopleforce_id',), name='uniq_emp_doc_folder_pf_id')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_peopleforce_id', models.CharField(db_index=True, max_length=120)),
                ('name', models.CharField(max_length=240)),
                ('document_type', models.CharField(choices=[('file', 'File'), ('link', 'Link'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('local_file', models.FileField(blank=True, upload_to='peopleforce_employee_documents/%Y/%m/')),
                ('file_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('file_download_error', models.TextField(blank=True)),
                ('legacy_payload', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='employees.employeedocumentfolder')),
            ],
            options={
                'ordering': ['employee', 'name'],
                'indexes': [models.Index(fields=['employee', 'document_type'], name='emp_doc_employee_type_idx'), models.Index(fields=['folder', 'document_type'], name='emp_doc_folder_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'legacy_peopleforce_id'), name='uniq_employee_document_pf_id')],
            },
        ),
    ]
