# Generated by Django 5.2.11 on 2026-06-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeedocumentfolder_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar_download_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar_file',
            field=models.FileField(blank=True, upload_to='employee_avatars/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar_source_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
