# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employee_avatar_download_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
