# Generated by Django 5.2.11 on 2026-06-25 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_workingpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('external_peopleforce_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('duration_months', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='probation_policy_active_idx')],
            },
        ),
        migrations.AddField(
            model_name='employeeemploymentstatus',
            name='probation_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_status_history', to='employees.probationpolicy'),
        ),
    ]
