# Generated by Django 5.2.11 on 2026-06-25 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_probationpolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('external_peopleforce_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='holiday_policy_active_idx')],
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='holiday_policy_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='employees.holidaypolicy'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_peopleforce_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('occurs_on', models.DateField()),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('working', models.BooleanField(default=False)),
                ('compensated_on', models.DateField(blank=True, null=True)),
                ('observed_on', models.DateField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'No recurrence'), ('yearly', 'Yearly')], default='none', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holidays', to='employees.holidaypolicy')),
            ],
            options={
                'ordering': ['occurs_on', 'name'],
                'indexes': [models.Index(fields=['policy', 'occurs_on'], name='holiday_policy_date_idx'), models.Index(fields=['is_active', 'occurs_on'], name='holiday_active_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('legacy_peopleforce_id', ''), _negated=True), fields=('legacy_peopleforce_id',), name='uniq_holiday_peopleforce_id'), models.UniqueConstraint(fields=('policy', 'occurs_on', 'name'), name='uniq_holiday_policy_date_name')],
            },
        ),
    ]
