# Generated by Django 4.2.18 on 2026-06-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_employeeformtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tab', models.CharField(choices=[('personal', 'Особисте'), ('work', 'Робота'), ('compensation', 'Компенсація')], db_index=True, default='personal', max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('is_system', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['tab', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='EmployeeFieldTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('columns', models.JSONField(blank=True, default=list, help_text='[{key,label,type}]')),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='employees.employeefieldgroup')),
            ],
            options={
                'ordering': ['group', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('system', 'Система'), ('text', 'Однорядковий текст'), ('textarea', 'Текст з багато рядків'), ('number', 'Число'), ('date', 'Дата'), ('select', 'Список'), ('employee', 'Вибір співробітника'), ('url', 'Посилання')], default='text', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('system_key', models.CharField(blank=True, help_text='Атрибут Employee для системних полів', max_length=80)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('show_in_summary', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='Варіанти для типу select')),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='employees.employeefieldgroup')),
            ],
            options={
                'ordering': ['group', 'order', 'id'],
            },
        ),
    ]
