# Generated by Django 4.2.18 on 2026-06-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_employeenote_emergencycontact_dependent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefield',
            name='field_type',
            field=models.CharField(choices=[('system', 'Система'), ('text', 'Однорядковий текст'), ('textarea', 'Текст з багато рядків'), ('number', 'Число'), ('date', 'Дата'), ('select', 'Список'), ('employee', 'Вибір співробітника'), ('url', 'Посилання'), ('boolean', 'Так/Ні')], default='text', max_length=20),
        ),
    ]
