# Generated by Django 4.2.18 on 2026-06-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_alter_employeefield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefieldtable',
            name='sync_target',
            field=models.CharField(blank=True, choices=[('', 'Без синхронізації'), ('positions', 'Посади → Employee + Position History'), ('employment', 'Робота → Employee + Employment Status')], default='', help_text='Чи синхронізувати рядки в доменні моделі (Employee/історія)', max_length=20),
        ),
    ]
