# Generated by Django 4.2.18 on 2026-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_skillcategory_skill_employeeskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecertificate',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employeecertificate',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='employeecertificate',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
