# Generated by Django 5.2.11 on 2026-06-24 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=160)),
                ('name', models.CharField(max_length=200)),
                ('clinic_code', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('direction_hint', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessEventRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_event_id', models.CharField(max_length=160)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('raw_user_id', models.CharField(blank=True, max_length=160)),
                ('raw_user_name', models.CharField(blank=True, max_length=200)),
                ('raw_device_id', models.CharField(blank=True, max_length=160)),
                ('raw_device_name', models.CharField(blank=True, max_length=200)),
                ('raw_message_code', models.CharField(blank=True, max_length=80)),
                ('raw_message_name', models.CharField(blank=True, max_length=160)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('uprox', 'UPROX'), ('zkteco', 'ZKTeco'), ('legacy_sunc_v4', 'Legacy sunc_v4'), ('unknown', 'Unknown')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('settings_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_user_id', models.CharField(max_length=160)),
                ('external_card_code', models.CharField(blank=True, max_length=160)),
                ('matched_by', models.CharField(blank=True, max_length=80)),
                ('confidence', models.CharField(choices=[('manual', 'Manual'), ('exact', 'Exact'), ('imported', 'Imported'), ('low', 'Low')], default='imported', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_identities', to='employees.employee')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to='skud.accesssystem')),
            ],
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField()),
                ('direction', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('quality', models.CharField(choices=[('ok', 'OK'), ('duplicate', 'Duplicate'), ('unknown_employee', 'Unknown employee'), ('suspicious_time', 'Suspicious time'), ('ignored', 'Ignored')], default='ok', max_length=30)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='skud.accessdevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='employees.employee')),
                ('raw_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_event', to='skud.accesseventraw')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='skud.accessidentity')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='accesseventraw',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_events', to='skud.accesssystem'),
        ),
        migrations.AddField(
            model_name='accessdevice',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='skud.accesssystem'),
        ),
        migrations.CreateModel(
            name='IntegrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('watermark_before', models.CharField(blank=True, max_length=160)),
                ('watermark_after', models.CharField(blank=True, max_length=160)),
                ('rows_fetched', models.PositiveIntegerField(default=0)),
                ('rows_inserted', models.PositiveIntegerField(default=0)),
                ('rows_ignored', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='skud.accesssystem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('period_type', models.CharField(choices=[('regular', 'Regular'), ('night', 'Night'), ('manual', 'Manual'), ('error', 'Error')], default='regular', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_periods', to='employees.employee')),
                ('source_events', models.ManyToManyField(blank=True, related_name='attendance_periods', to='skud.accessevent')),
                ('calculation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_periods', to='skud.integrationrun')),
            ],
            options={
                'ordering': ['date', 'start_at'],
            },
        ),
        migrations.AddField(
            model_name='accesseventraw',
            name='integration_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_events', to='skud.integrationrun'),
        ),
        migrations.CreateModel(
            name='TimeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('before_summary', models.JSONField(blank=True, default=dict)),
                ('after_summary', models.JSONField(blank=True, default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_adjustments', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkDaySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('planned_minutes', models.PositiveIntegerField(default=0)),
                ('actual_minutes', models.PositiveIntegerField(default=0)),
                ('first_entry_at', models.DateTimeField(blank=True, null=True)),
                ('last_exit_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('late', 'Late'), ('absent', 'Absent'), ('missing_entry', 'Missing entry'), ('missing_exit', 'Missing exit'), ('manual_review', 'Manual review'), ('locked', 'Locked')], default='manual_review', max_length=30)),
                ('exception_count', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workday_summaries', to='employees.employee')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_workdays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'employee__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['employee', 'occurred_at'], name='access_event_employee_time_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['quality', 'occurred_at'], name='access_event_quality_time_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['device', 'occurred_at'], name='access_event_device_time_idx'),
        ),
        migrations.AddIndex(
            model_name='accessidentity',
            index=models.Index(fields=['employee', 'is_active'], name='accid_employee_active_idx'),
        ),
        migrations.AddIndex(
            model_name='accessidentity',
            index=models.Index(fields=['system', 'external_card_code'], name='access_identity_card_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessidentity',
            constraint=models.UniqueConstraint(fields=('system', 'external_user_id'), name='uniq_access_identity_system_user'),
        ),
        migrations.AddIndex(
            model_name='accessdevice',
            index=models.Index(fields=['system', 'is_active'], name='accdev_system_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessdevice',
            constraint=models.UniqueConstraint(fields=('system', 'external_id'), name='uniq_access_device_system_external'),
        ),
        migrations.AddIndex(
            model_name='integrationrun',
            index=models.Index(fields=['system', 'job_name', '-started_at'], name='integration_run_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationrun',
            index=models.Index(fields=['status', '-started_at'], name='integration_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceperiod',
            index=models.Index(fields=['employee', 'date'], name='attperiod_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='accesseventraw',
            index=models.Index(fields=['system', 'occurred_at'], name='raw_event_system_time_idx'),
        ),
        migrations.AddIndex(
            model_name='accesseventraw',
            index=models.Index(fields=['raw_user_id', 'occurred_at'], name='raw_event_user_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='accesseventraw',
            constraint=models.UniqueConstraint(fields=('system', 'source_event_id'), name='uniq_raw_event_system_source'),
        ),
        migrations.AddIndex(
            model_name='timeadjustment',
            index=models.Index(fields=['employee', 'date'], name='timeadj_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workdaysummary',
            index=models.Index(fields=['date', 'status'], name='workday_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workdaysummary',
            index=models.Index(fields=['employee', 'date'], name='workday_employee_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='workdaysummary',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='uniq_workday_employee_date'),
        ),
    ]
